### ISSUE TITLE
Some issues about [gameplay] (clicking on tiles) & suggestions

### ISSUE THREAD

**Issue by letangphuquy** [zukahai/catch-bugs-game#2]
This game is quite lag at current version. Sometimes I click but a piece won't move, or still move but only after a while. 
Also, I noticed that if I click on an empty corner of the tile, such that my mouse's location still in the "square", the tile still rotate. I expect them to rotate only when clicked on the blue part. Maybe they're implemented as square images?
As I can see, there're 2 types of rotate: 90 degrees, and flip horizontally. But I don't know for sure when the second type of rotate will be activated so it'd be nice if it is included in the instruction.

**Comment by letangphuquy** [comment]
It'd be nice if there are hints because I find that the game's quite hard.

**Comment by letangphuquy** [comment]
It'd be nice if there are some nice music to help people relax while playing.

**Comment by zukahai** [comment]
Thank you for comment.  I have added a tutorial to make it easier for users to understand.  I will continue to take note of other comments.
